### ISSUE TITLE
Custom upstream DNS servers can be on non-standard ports

### ISSUE THREAD

**Issue by dschaper** [pi-hole/docs#162]
https://github.com/pi-hole/docs/blob/master/docs/guides/upstream-dns-providers.md

Add verbiage to Custom DNS to note that upstream can be on `#<port>` notation.

**Comment by starmagoo** [comment]
This does not work. I'm on pi.hole 5.0 and i try to use unbound on 5335 --> 127.0.0.1#5335

**Comment by dschaper** [comment]
I don't understand your issue.

**Comment by starmagoo** [comment]
I have pi-hole 5.0 running and it works fine. However, I want to run it with its own restrictive DNS server, so I installed unboud. Unbound works. I can resolve DNS names with the command "dig". Unbound listens on port 5335, because pi-hole already uses 53. If I now enter unbound as DNS server in the pi-hole web interface (e.g. 127.0.0.1#5335 or 192.168.178.2#5335), DNS resolution no longer works. This seems to be the case for every server where the port is different from port 53. None of them work. So I suspect a bug in Pi-Hole that the custom port different from port 53 does not work.

**Comment by dschaper** [comment]
This is the documentation repository, if you have an issue with running Pi-hole then please visit https://discourse.pi-hole.net for help.
