### ISSUE TITLE
Unbound Issues with raspbian light

### ISSUE THREAD

**Issue by thromeaway** [pi-hole/docs#308]
It seems like https://docs.pi-hole.net/guides/unbound/ needs to be refreshed as unbound isnt working with the given confoguration on a clean raspbian light installation. When using the dig command a server timeout comes.

Ref https://github.com/NLnetLabs/unbound/issues/237

**Comment by thromeaway** [comment]
It seems like there were issues with certain ports and i wanst able to replicate it with 5335 properly. I think this can be considered closed. Any plans to integrate unbound in pihole?

**Comment by PromoFaux** [comment]
Ah, I just noticed from your other issue thread that you were getting timeouts on `5353`, which may be where it was going wrong

`5353` was changed in the docs recently I think because of a conflict with another package that uses that port by default.

At this stage, no there are no plans. `pihole-FTL` is based around `dnsmasq`

**Comment by thromeaway** [comment]
I havent commited to github yet and i mostly use it for reporting issues. Maybe there could be added a warning that the port changed as many people are still used to the old port and oversee it easily haha. Thanks for your patience.
